-- =============================================================================
-- V1 Baseline: extensions and shared database infrastructure.
--
-- Conventions used by every table in this schema:
--   * Primary keys are snowflake IDs generated by the application (assign_id),
--     never database sequences, so IDs stay unique across future shards.
--   * Money is stored as NUMERIC(19,4). NEVER use float/double for money.
--   * Quantities (tonnage, kg) are stored as NUMERIC(18,3).
--   * Every business table carries created_at/updated_at/created_by/updated_by
--     plus a soft-delete flag `deleted` (0 = alive, 1 = deleted).
--   * updated_at is maintained by a trigger so the application can never forget
--     to bump it.
-- =============================================================================

-- Fuzzy text search for enterprise / commodity name lookups.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- -----------------------------------------------------------------------------
-- Trigger function: stamp updated_at on every UPDATE.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION set_updated_at() IS
    'BEFORE UPDATE trigger: stamps updated_at with the current timestamp.';

-- -----------------------------------------------------------------------------
-- Helper used by later migrations to attach the trigger in one line:
--     SELECT attach_updated_at_trigger('t_enterprise');
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION attach_updated_at_trigger(p_table TEXT)
RETURNS VOID AS $$
BEGIN
    EXECUTE format(
        'CREATE TRIGGER trg_%1$s_updated_at
         BEFORE UPDATE ON %1$I
         FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
        p_table
    );
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION attach_updated_at_trigger(TEXT) IS
    'Creates a BEFORE UPDATE trigger named trg_<table>_updated_at on the given table.';
