async (page) => {
  const origin = 'http://localhost:38080'
  const assert = (value, label) => { if (!value) throw new Error(label) }
  const login = async username => {
    await page.goto(origin + '/login')
    await page.getByLabel('用户名', { exact: true }).fill(username)
    await page.getByLabel('密码', { exact: true }).fill('Admin@123')
    await page.getByRole('button', { name: /登\s*录/, exact: true }).click()
    await page.waitForURL(origin + '/')
  }
  const logout = async () => {
    await page.locator('.account-trigger').click()
    await page.getByText('退出登录', { exact: true }).click()
    await page.waitForURL(origin + '/')
  }
  await login('admin')
  await page.goto(origin + '/admin/enterprises')
  const row = page.getByRole('row').filter({ hasText: '华东金属材料有限公司' })
  await row.getByRole('button', { name: /冻\s*结/, exact: true }).waitFor()
  await page.getByLabel('后台关键词', { exact: true }).fill('华东金属材料')
  await page.getByLabel('后台关键词', { exact: true }).press('Enter')
  await page.getByText('浙江建工物资有限公司', { exact: true }).waitFor({ state: 'hidden' })
  await row.getByRole('button', { name: /冻\s*结/, exact: true }).click()
  await page.getByRole('button', { name: '确认保存' }).click()
  await page.getByText('请填写操作原因', { exact: true }).waitFor()
  await page.getByLabel('操作原因', { exact: true }).fill('隔离浏览器验收冻结')
  await page.getByRole('button', { name: '确认保存' }).click()
  await row.getByRole('button', { name: /解\s*冻/, exact: true }).waitFor()
  await row.getByRole('button', { name: /解\s*冻/, exact: true }).click()
  await page.getByRole('button', { name: '确认保存' }).click()
  await row.getByRole('button', { name: /冻\s*结/, exact: true }).waitFor()
  await page.goto(origin + '/admin/users')
  const auditor = page.getByRole('row').filter({ hasText: 'auditor01' })
  await auditor.getByRole('button', { name: '分配角色' }).click()
  await page.getByRole('dialog').getByText('平台审计员', { exact: true }).first().waitFor()
  await page.getByRole('button', { name: /取\s*消/, exact: true }).click()
  await page.goto(origin + '/admin/audit')
  await page.getByText('冻结企业', { exact: true }).first().waitFor()
  await page.locator('.ant-spin-spinning').waitFor({ state: 'hidden' })
  await page.waitForFunction(() => [...document.querySelectorAll('.ant-spin-container')].every(node => getComputedStyle(node).opacity === '1'))
  await page.screenshot({ path: '/workspace/.local/browser/admin-desktop.png', fullPage: true })
  for (const width of [1440, 1280, 1024, 768, 390]) {
    await page.setViewportSize({ width, height: 900 })
    for (const route of ['/admin/enterprises', '/admin/users', '/market', '/trading', '/enterprise']) {
      await page.goto(origin + route)
      await page.waitForLoadState('networkidle')
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `${route} 在 ${width}px 全页横向溢出`)
    }
  }
  await page.goto(origin + '/admin/enterprises')
  await page.getByText('华东金属材料有限公司', { exact: true }).waitFor()
  await page.locator('.ant-spin-spinning').waitFor({ state: 'hidden' })
  await page.waitForFunction(() => [...document.querySelectorAll('.ant-spin-container')].every(node => getComputedStyle(node).opacity === '1'))
  await page.screenshot({ path: '/workspace/.local/browser/admin-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1280, height: 900 })
  await logout()
  await login('auditor01')
  await page.goto(origin + '/admin/enterprises')
  await page.getByText('华东金属材料有限公司', { exact: true }).waitFor()
  assert(await page.getByRole('button', { name: /冻\s*结/, exact: true }).count() === 0, '审计员出现冻结按钮')
  assert(await page.getByRole('link', { name: '账号与角色', exact: true }).count() === 0, '审计员出现无权限菜单')
  await page.goto(origin + '/admin/users')
  await page.getByText('无权访问此管理页面', { exact: true }).waitFor()
  await logout()
  await login('buyer01')
  assert(await page.getByRole('link', { name: '管理后台', exact: true }).count() === 0, '企业会员出现后台菜单')
  await page.goto(origin + '/admin/enterprises')
  await page.getByText('无权访问此管理页面', { exact: true }).waitFor()
  await page.goto(origin + '/trading?tab=orders')
  await page.getByRole('tab', { name: /我的订单/ }).waitFor()
  await page.setViewportSize({ width: 390, height: 844 })
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), '订单表手机全页溢出')
  await page.goto(origin + '/')
  await page.getByRole('link', { name: '跳到页面内容' }).focus()
  await page.keyboard.press('Enter')
  assert(await page.locator('#main-content').evaluate(el => document.activeElement === el), '跳过导航未聚焦正文')
  console.log('企业冻结恢复、角色表单、审计员只读、会员菜单、五宽度布局及键盘导航通过')
}
