async (page) => {
  const base = 'http://localhost:48080'
  const assert = (condition, text) => { if (!condition) throw new Error(text) }
  const stats = async () => (await (await page.request.get('http://host.docker.internal:48082/stats')).json()).count
  const login = async (username) => {
    await page.goto(`${base}/login`)
    await page.getByLabel('用户名', { exact: true }).fill(username)
    await page.getByLabel('密码', { exact: true }).fill('Admin@123')
    await page.getByRole('button', { name: /登\s*录/, exact: true }).click()
    await page.waitForURL(`${base}/`)
  }
  await login('admin')
  await page.getByRole('link', { name: '管理后台', exact: true }).click()
  await page.getByRole('link', { name: '模型配置', exact: true }).click()
  await page.getByRole('heading', { name: '平台模型配置' }).waitFor()
  await page.getByLabel('API 地址', { exact: true }).waitFor()
  const before = await stats()
  const canary = 'offline-browser-secret-canary'
  await page.getByLabel('API 地址', { exact: true }).fill('http://advisor-mock:8080/v1')
  await page.getByLabel('模型 ID', { exact: true }).fill('offline-browser-model')
  await page.getByLabel('API Key', { exact: true }).fill(canary)
  await page.getByRole('button', { name: 'save 保存配置', exact: true }).click()
  await page.getByText('后台配置', { exact: true }).waitFor()
  await page.waitForFunction(() => document.querySelector('#apiKey')?.value === '')
  assert(await stats() === before, '保存自动调用了模型')
  assert(await page.getByLabel('API Key', { exact: true }).inputValue() === '', '保存后 API Key 未清空')
  assert(!(await page.evaluate(() => JSON.stringify(localStorage) + JSON.stringify(sessionStorage))).includes(canary), 'Key 写入浏览器持久存储')
  await page.getByRole('button', { name: '测试已保存配置' }).click()
  await page.getByText('连接正常，工具调用已验证', { exact: true }).waitFor()
  assert(await stats() === before + 2, '模型工具往返次数错误')
  await page.reload()
  await page.getByText('后台配置', { exact: true }).waitFor()
  assert(await page.getByLabel('模型 ID', { exact: true }).inputValue() === 'offline-browser-model', '模型修改刷新未保留')
  assert(await page.getByLabel('API Key', { exact: true }).inputValue() === '', '刷新泄漏 Key')
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: '/workspace/.local/browser/advisor-admin-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '模型配置手机页面横向溢出')
  await page.screenshot({ path: '/workspace/.local/browser/advisor-admin-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByLabel('清除已保存密钥', { exact: true }).click()
  await page.getByRole('button', { name: 'save 保存配置', exact: true }).click()
  await page.getByText('待设置密钥', { exact: true }).waitFor()
  assert(await stats() === before + 2, '清除 Key 调用了模型')
  await page.getByRole('button', { name: '恢复环境配置' }).click()
  await page.getByRole('button', { name: /^恢\s*复$/, exact: true }).click()
  await page.getByText('.env 配置', { exact: true }).waitFor()
  await login('auditor01')
  await page.goto(`${base}/admin/model`)
  await page.getByText('当前账号只有查看权限').waitFor()
  assert(await page.getByRole('button', { name: 'save 保存配置', exact: true }).count() === 0, '审计员可以修改配置')
  await login('buyer01')
  await page.goto(`${base}/admin/model`)
  await page.getByText('无权访问', { exact: true }).waitFor()
  const httpStatus = await page.evaluate(async () => {
    const { state } = JSON.parse(localStorage.getItem('spotlink-auth'))
    const response = await fetch('/api/admin/advisor-model', { headers: { Authorization: `Bearer ${state.accessToken}` } })
    return response.status
  })
  assert(httpStatus === 403, '企业用户可直接读取模型后台')
  await page.goto(`${base}/advisor`)
  await page.getByText('平台模型待配置', { exact: true }).first().waitFor()
  console.log('模型后台真实页面：保存不调用、工具测试、持久化、Key 清空、恢复、权限和响应式通过。')
}
